---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library(readxl)
Wholesale_Customers <- read_excel("C://Users/Rahmatia/Documents/Kmeans/Wholesale Customers.xlsx")
View(Wholesale_Customers)
summary(Wholesale_Customers)
```
```{r}
Wholesale_Customers.new <- Wholesale_Customers[, 1:4]
Wholesale_Customers.class <- Wholesale_Customers[, "Grocery"]
set.seed(1356)
result <- kmeans(Wholesale_Customers.new, 3)
```

```{r}
par(mfrow=c(2,2), mar=c(5,4,2,2))
plot(Wholesale_Customers.new[, c(1,2)], col=result$cluster)
plot(Wholesale_Customers.new[, c(1,2)], col=Wholesale_Customers.class)
plot(Wholesale_Customers.new[, c(3,4)], col=result$cluster)
plot(Wholesale_Customers.new[, c(3,4)], col=Wholesale_Customers.class)
```
```{r}
result$tot.withinss
```

```{r}
attributes(result)$names
```

```{r}
Wholesale_Customers.new$cluster <- factor(result$cluster)
centers <- as.data.frame(result$centers)
library(ggplot2)
ggplot() + 
  geom_point(data=Wholesale_Customers.new, aes(x=Channel, y=Region,color=cluster))  +
  geom_point(data=centers, aes(x=Channel, y=Region, color="Center"), 
             size=52, alpha=.3, show.legend = FALSE)
```
```{r}
set.seed (2)
Region <- matrix (rnorm (50*2) , ncol =2)
Region[1:25 ,1] <- Region[1:25 ,1] + 3
Region[1:25 ,2]<- Region[1:25 ,2] - 4
plot(Wholesale_Customers)
```
```{r}
Wholesale_Customers <- kmeans(Region, 2)
plot(Region, col = (Wholesale_Customers$cluster +1))
```




